name: Publish

concurrency: 
    group: Publish
    cancel-in-progress: true

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    install:
        uses: Klasmart-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@v3.1.0
        secrets:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

    lint:
        needs: [install]
        uses: Klasmart-Engineering/github-action-workflows/.github/workflows/npm-lint.yml@v3.1.0

    confirm-publish:
        needs: [lint]
        runs-on: ubuntu-latest
        environment: latest
        steps:
            - name: Debug message
              run: echo Publish confirmed

    publish:
        needs: [confirm-publish]
        uses: Klasmart-Engineering/github-action-workflows/.github/workflows/npm-publish.yml@v3.1.0
        secrets:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
